---
platform: linux
image_resource:
  type: registry-image
  source:
    repository: internalpcfplatformautomation/ci
    tag: testing

inputs:
  - name: deployments
outputs:
  - name: deployments
params:
  DEPLOYMENT:

run:
  path: bash
  args:
    - -c
    - |
      set -eux

      cd deployments/"$DEPLOYMENT"
      rm -Rf state.yml
      rm -Rf terraform.tfstate

      git config --global user.name "platform-automation"
      git config --global user.email "platformautomation@groups.vmware.com"
      git add -A
      git commit -m "removed state for $DEPLOYMENT" || true
